<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-question.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => 'Erantzun 1',
		'a_convert_to_c_on' => 'Erantzun hau iruzkin bihurtu hemen:',
		'a_convert_to_c' => 'Erantzun hau iruzkin bihurtu',
		'a_convert_warn_cs' => 'Kontuz: elkarrizketa hau ezin da bihurtu eta erantzunaren iruzkinak mugituko ditu.',
		'a_convert_warn' => 'Kontuz: elkarrizketa hau ezin da bihurtu.',
		'a_notify_email' => 'Posta elektronikoz ohartarazi nire erantzuna hautatzen edo iruzkintzen bada:',
		'a_notify_label' => 'Posta elektronikoz ohartarazi nire erantzuna hautatzen edo iruzkintzen bada',
		'a_notify_x_label' => 'Posta elektronikoz ohartarazi (^) nire erantzuna hautatzen edo iruzkintzen bada',
		'a_waiting_your_approval' => 'Erantzun hau zure onespenaren zain dago',
		'a_your_waiting_approval' => 'Zure erantzuna laster berrikusi eta onartuko da.',
		'add_answer_button' => 'Erantzun',
		'add_comment_button' => 'Iruzkindu',
		'add_q_favorites' => 'Galdera hau nire gogokoenera gehitu',
		'anon_name_label' => 'Erakusteko izena (hautazkoa):',
		'answer_button' => 'erantzun',
		'answer_limit' => 'Erantzun gehiegi jaso dira - mesedez, saiatu berriro ordubete barru',
		'answer_must_be_approved' => 'Zure kontua baieztatu behar da galderak erantzuteko.',
		'answer_must_confirm' => 'Mesedez, ^5zure posta elektronikoa baieztatu^6 galdera hau erantzuteko.',
		'answer_must_login' => 'Mesedez, ^1saioa hasi^2 edo ^3erregistratu^4 galdera hau erantzuteko.',
		'answer_q_popup' => 'Galdera hau erantzun',
		'approve_button' => 'baieztatu',
		'ask_button' => 'Galdera egin',
		'ask_follow_from_a' => 'Zure galdera erantzun honekin erlazionatuko da:',
		'ask_follow_title' => 'Erlazionatutako galdera egin',
		'ask_limit' => 'Galdera gehiegi jaso dira - mesedez, saiatu berriro ordubete barru',
		'ask_must_be_approved' => 'Zure kontua baieztatu behar da galderak egiteko.',
		'ask_must_confirm' => 'Mesedez, ^5zure posta elektronikoa baieztatu^6 galdera bat egiteko.',
		'ask_must_login' => 'Mesedez, ^1saioa hasi^2 edo ^3erregistratu^4 galdera bat erantzuteko.',
		'ask_same_q' => 'Jarraitu baino lehen, mesedez, zure galdera erantzunda ez dagoela egiaztatu:',
		'ask_title' => 'Galdera egin',
		'c_notify_email' => 'Posta elektronikoz ohartarazi helbide honetara nire iruzkinaren ostean iruzkin bat gehitzen bada:',
		'c_notify_label' => 'Posta elektronikoz ohartarazi nire iruzkinaren ostean iruzkin bat gehitzen bada',
		'c_notify_x_label' => 'Posta elektronikoz ohartarazi (^) nire iruzkinaren ostean iruzkin bat gehitzen bada',
		'c_waiting_your_approval' => 'Iruzkin hau zure onespenaren zain dago',
		'c_your_waiting_approval' => 'Zure iruzkina laster berrikusi eta onartuko da.',
		'category_js_note' => 'Kategoria bat hautatzeko, mesedez, Javascript gaitu zure nabigatzailean.',
		'category_required' => 'Mesedez, kategoria hautatu',
		'category_ask_not_allowed' => 'Ez daukazu kategoria honetan galdetzeko baimena',
		'claim_button' => 'Testu hau nirea da',
		'clear_flags_button' => 'markak garbitu',
		'clear_flags_popup' => 'Erabiltzaile guztien markak ezabatu',
		'close_button' => 'itxi',
		'close_duplicate_error' => 'Bikoiztutako galdera ez da aurkitu - mesedez, beste galdera baten URL helbidearen zenbakia sartu, adibidez, 123.',
		'close_duplicate' => 'Hau beste galderaren kopia bat da',
		'close_form_button' => 'Galdera itxi',
		'close_form_title' => 'Galdera hau itxi',
		'close_original_note' => 'Galderaren URL helbidearen zenbakia ere sartu dezakezu, adibidez, 123.',
		'close_original_title' => 'Galdera originalaren URL helbidea:',
		'close_q_popup' => 'Galdera hau erantzun berriei itxi',
		'close_reason_title' => 'Galdera hau ixteko arrazoia:',
		'closed_as_duplicate' => 'honen kopia izateagatik itxita:',
		'closed_with_note' => 'nota honekin itxita:',
		'comment_a_popup' => 'Erantzun honetan iruzkina gehitu',
		'comment_button' => 'iruzkindu',
		'comment_limit' => 'Iruzkin gehiegi jaso dira - mesedez, saiatu berriro ordubete barru',
		'comment_must_be_approved' => 'Zure kontua baieztatu behar da iruzkinak idazteko.',
		'comment_must_confirm' => 'Mesedez, ^5zure posta elektronikoa baieztatu^6 iruzkin bat idazteko.',
		'comment_must_login' => 'Mesedez, ^1saioa hasi^2 edo ^3erregistratu^4 iruzkin bat gehitzeko.',
		'comment_on_a' => 'Erantzun honetan: ',
		'comment_on_q' => 'Galdera honetan: ',
		'comment_q_popup' => 'Galdera honetan iruzkina idatzi',
		'delete_a_popup' => 'Erantzun hau betirako ezabatu',
		'delete_button' => 'ezabatu',
		'delete_c_popup' => 'Iruzkin hau betirako ezabatu',
		'delete_q_popup' => 'Galdera hau betirako ezabatu',
		'duplicate_content' => 'Zure argitalpena bikoiztuta dagoela dirudi.',
		'edit_a_popup' => 'Erantzun hau editatu',
		'edit_a_title' => 'Erantzuna editatu',
		'edit_button' => 'editatu',
		'edit_c_popup' => 'Iruzkin hau editatu',
		'edit_c_title' => 'Iruzkina editatu',
		'edit_must_confirm' => 'Mesedez, ^5zure posta elektronikoa baieztatu^6 editatzeko.',
		'edit_must_login' => 'Mesedez, ^1saioa hasi^2 edo ^3erregistratu^4 editatzeko.',
		'edit_q_popup' => 'Galdera hau editatu',
		'edit_q_title' => 'Galdera editatu',
		'example_tags' => 'Adibidezko etiketak: ',
		'flag_a_popup' => 'Erantzun hau spam edo ezegoki moduan markatu',
		'flag_button' => 'markatu',
		'flag_c_popup' => 'Iruzkin hau spam edo ezegoki moduan markatu',
		'flag_hide_button' => 'markatu eta ezkutatu',
		'flag_limit' => 'Argitalpen gehiegi markatu dira - mesedez, saiatu berriro ordubete barru',
		'flag_must_confirm' => 'Mesedez, ^5zure posta elektronikoa baieztatu^6 argitalpenak markatzeko.',
		'flag_must_login' => 'Mesedez, ^1saioa hasi^2 edo ^3erregistratu^4 argitalpenak markatzeko.',
		'flag_not_allowed' => 'Ezin da hau markatu',
		'flag_q_popup' => 'Galdera hau spam edo ezegoki moduan markatu',
		'follow_a_popup' => 'Erantzun honekin erlazionatutako galdera berria egin',
		'follow_button' => 'erlazionatutako galdera egin',
		'follows_a' => 'honen erantzun batekin erlazionatuta:',
		'follows_q' => 'galderari buruz:',
		'hide_a_popup' => 'Erantzun hau ezkutatu',
		'hide_button' => 'ezkutatu',
		'hide_c_popup' => 'Iruzkin hau ezkutatu',
		'hide_q_popup' => 'Galdera hau ezkutatu',
		'matching_tags' => 'Bat etortzen diren etiketak: ',
		'max_tags_x' => 'Gehienez ^ etiketa baimentzen dira',
		'min_tags_x' => 'Mesedez, gutxienez ^ etiketa jarri',
		'notify_email_note' => 'Pribatutasuna: Zure posta elektronikoa oharpen hauek bidaltzeko bakarrik erabiliko da.',
		'q_category_label' => 'Kategoria:',
		'q_content_label' => 'Galderarentzako informazio gehiago:',
		'q_hidden_author' => 'Galdera hau bere egileagatik ezkutatuta izan da',
		'q_hidden_flagged' => 'Galdera hau markatu eta ezkutatu da',
		'q_hidden_other' => 'Galdera hau ezkutatuta izan da',
		'q_notify_email' => 'Posta elektronikoz ohartarazi nire galdera erantzuten edo iruzkintzen bada:',
		'q_notify_label' => 'Posta elektronikoz ohartarazi nire galdera erantzuten edo iruzkintzen bada',
		'q_notify_x_label' => 'Posta elektronikoz ohartarazi (^) nire galdera erantzuten edo iruzkintzen bada',
		'q_tags_comma_label' => 'Etiketak - koma erabili (,) banatzaile moduan:',
		'q_tags_label' => 'Etiketak - gidoia erabili hitzak konbinatzeko:',
		'q_title_label' => 'Zure galdera esaldi batean:',
		'q_waiting_approval' => 'Galdera hau onespenaren zain dago',
		'q_waiting_your_approval' => 'Galdera hau zure onespenaren zain dago',
		'q_your_waiting_approval' => 'Zure galdera laster berrikusi eta onartuko da.',
		'recat_button' => 'kategoriaz aldatu',
		'recat_popup' => 'Galdera honen kategoria aldatu',
		'recat_q_title' => 'Galdera kategoriaz aldatu',
		'reject_button' => 'ezeztatu',
		'remove_q_favorites' => 'Galdera hau nire gogokoenetik ezabatu',
		'reopen_button' => 'berriz ireki',
		'reply_button' => 'erantzun',
		'reply_c_popup' => 'Iruzkin hau erantzun',
		'reshow_button' => 'berriz erakutsi',
		'retag_button' => 'etiketaz aldatu',
		'retag_cat_popup' => 'Galdera honen kategoria edo etiketak aldatu',
		'retag_popup' => 'Galdera honen etiketak aldatu',
		'retag_q_title' => 'Galdera etiketaz aldatu',
		'save_silent_label' => 'Adierazpenak egin gabe gorde editatu egin dela ezkutatzeko',
		'select_popup' => 'Sakatu erantzun onena bezala hautatzeko',
		'select_text' => 'Erantzun hoberena',
		'show_1_comment' => 'Iruzkin 1 erakutsi',
		'show_1_previous_comment' => 'Aurretiko iruzkin 1 erakutsi',
		'show_x_comments' => '^ iruzkin erakutsi',
		'show_x_previous_comments' => 'Aurretiko ^ iruzkin erakutsi',
		'unflag_button' => 'marka kendu',
		'unflag_popup' => 'Gehitutako marka kendu',
		'unselect_popup' => 'Sakatu hautaketa ezabatzeko',
		'x_answers_title' => '^ Erantzun',
		'your_answer_title' => 'Zure erantzuna',
		'your_comment_a' => 'Zure iruzkina erantzun honetan:',
		'your_comment_q' => 'Zure iruzkina galdera honetan:',
		'approve_a_popup' => "Erantzun hau baieztatu",
		'approve_c_popup' => "Iruzkin hau baieztatu",
		'approve_q_popup' => "Galdera hau baieztatu",
		'claim_a_popup' => "Erantzun hau zure erabiltzaile kontura esleitu",
		'claim_c_popup' => "Iruzkin hau zure erabiltzaile kontura esleitu",
		'claim_q_popup' => "Galdera hau zure erabiltzaile kontura esleitu",
		'reject_a_popup' => "Erantzun hau ezeztatu",
		'reject_c_popup' => "Iruzkin hau ezeztatu",
		'reject_q_popup' => "Galdera hau ezeztatu",
		'reopen_q_popup' => "Galdera hau berriz ireki",
		'reshow_a_popup' => "Erantzun hau berriz erakutsi",
		'reshow_c_popup' => "Iruzkin hau berriz erakutsi",
		'reshow_q_popup' => "Galdera hau berriz erakutsi",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
