<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => 'Erantzun 1',
		'1_comment' => 'Iruzkin 1',
		'1_day' => 'Egun 1',
		'1_disliked' => 'Boto negatibo 1',
		'1_flag' => 'Marka 1',
		'1_hour' => 'Ordu 1',
		'1_liked' => 'Positibo 1',
		'1_minute' => 'Minutu 1',
		'1_month' => 'Hilabete 1',
		'1_point' => 'Puntu 1',
		'1_question' => 'Galdera 1',
		'1_second' => 'Segundu 1',
		'1_tag' => 'Etiketa 1',
		'1_user' => 'Erabiltzaile 1',
		'1_view' => 'Ikusi 1',
		'1_vote' => 'Boto 1',
		'1_week' => 'Aste 1',
		'1_year' => 'Urte 1',
		'add_category_x_favorites' => '^ kategoria nire gogokoenera gehitu',
		'add_favorites' => 'Nire gogokoenera gehitu',
		'add_tag_x_favorites' => '^ etiketa nire gogokoenera gehitu',
		'all_categories' => 'Kategoria guztiak',
		'anonymous' => 'ezezaguna',
		'answer_edited' => 'erantzuna editatu da',
		'answer_reshown' => 'erantzuna berriz erakusten da',
		'answer_selected' => 'erantzuna hautatu da',
		'answered_qs_in_x' => 'Gehien erantzun diren galderak ^ -(e)n',
		'answered_qs_title' => 'Gehien erantzundako galderak',
		'answered' => 'erantzunda',
		'asked_related_q' => 'erlazionatutako galdera',
		'asked' => 'galdetuta',
		'by_x' => '^ -(r)engatik',
		'cancel_button' => 'Ezeztatu',
		'closed' => 'itxita',
		'comment_edited' => 'iruzkina editatu da',
		'comment_moved' => 'iruzkina mugitu da',
		'comment_reshown' => 'iruzkina berriz erakusten da',
		'commented' => 'iruzkinduta',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^month ^day, ^year',
		'date_format_this_year' => '^month ^day',
		'date_month_1' => 'Urt',
		'date_month_2' => 'Ots',
		'date_month_3' => 'Mar',
		'date_month_4' => 'Api',
		'date_month_5' => 'Mai',
		'date_month_6' => 'Eka',
		'date_month_7' => 'Uzt',
		'date_month_8' => 'Abu',
		'date_month_9' => 'Ira',
		'date_month_10' => 'Urr',
		'date_month_11' => 'Aza',
		'date_month_12' => 'Abe',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'editatuta',
		'field_required' => 'Mesedez, zerbait idatzi eremu honetan',
		'general_error' => 'Errore bat egon da zerbitzarian - mesedez, berriro saiatu.',
		'hidden' => 'ezkutatuta',
		'highest_users' => 'Puntu gehien lortu dituzten erabiltzaileak',
		'hot_qs_in_x' => '^ -(e)ko galdera nabariak',
		'hot_qs_title' => 'Galdera nabariak',
		'image_not_read' => 'Gerta liteke irudia irakurria ez izatea. Mesedez, hemengo bat igo: ^',
		'image_too_big_x_pc' => 'Irudi hau oso handia da. Mesedez, ^% -(e)ra txikitu eta berriro saiatu',
		'in_category_x' => '^ -(e)n',
		'ip_address_x' => '^ IP helbidea',
		'logged_in_x' => 'Kaixo ^',
		'max_length_x' => 'Gehienezko luzeera ^ karaktere dira',
		'me' => 'ni',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Mesedez, informazio gehiago eman - gutxienez ^ karaktere',
		'max_upload_size_x' => 'Igoera tamaina maximoa ^ da',
		'moved' => 'mugituta',
		'nav_activity' => 'Aktibitate guztia',
		'nav_admin' => 'Admin',
		'nav_ask' => 'Galdera egin',
		'nav_categories' => 'Kategoriak',
		'nav_feedback' => 'Feedback-a bidali',
		'nav_home' => 'Hasiera',
		'nav_hot' => 'Nabariak',
		'nav_login' => 'Sartu',
		'nav_logout' => 'Irten',
		'nav_most_answers' => 'Gehien erantzundakoak',
		'nav_most_recent' => 'Berriak',
		'nav_most_views' => 'Gehien ikusitakoak',
		'nav_most_votes' => 'Bozkatuenak',
		'nav_no_answer' => 'Erantzun gabea',
		'nav_no_selected_answer' => 'Hautatutako erantzun gabea',
		'nav_no_upvoted_answer' => 'Boto positiboa duen erantzun gabea',
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Galderak',
		'nav_register' => 'Erregistratu',
		'nav_tags' => 'Etiketak',
		'nav_unanswered' => 'Erantzun gabeak',
		'nav_updates' => 'Nire eguneraketak',
		'nav_users' => 'Erabiltzaileak',
		'no_active_users' => 'Ez dira erabiltzaile aktiboak aurkitu',
		'no_answers_found' => 'Ez dira erantzunak aurkitu',
		'no_answers_in_x' => 'Ez dira erantzunak aurkitu ^ -(e)n',
		'no_categories_found' => 'Ez dira kategoriak aurkitu',
		'no_category' => 'Ez daude kategoriak',
		'no_comments_found' => 'Ez dira iruzkinak aurkitu',
		'no_comments_in_x' => 'Ez dira iruzkinak aurkitu ^ -(e)n',
		'no_questions_found' => 'Ez dira galderak aurkitu',
		'no_questions_in_x' => 'Ez dira galderak aurkitu ^ -(e)n',
		'no_related_qs_title' => 'Ez dira erlazionatutako galderak aurkitu',
		'no_results_for_x' => 'Ez dira emaitzak aurkitu ^ -(e)rako',
		'no_tags_found' => 'Ez dira etiketak aurkitu',
		'no_una_questions_found' => 'Ez dira erantzun gabeko galderak aurkitu',
		'no_una_questions_in_x' => 'Erantzun gabeko galdera barik ^ -(e)n',
		'no_unselected_qs_found' => 'Ez dago erantzun hautatua ez duen galdera',
		'no_unupvoteda_qs_found' => 'Ez dago boto positiboa duen erantzuna ez duen galdera',
		'page_label' => 'Orrialdea:',
		'page_next' => 'hurrengoa',
		'page_not_found' => 'Orrialdea ez da aurkitu',
		'page_prev' => 'aurrekoa',
		'popular_tags' => 'Gehien erabiltzen diren etiketak',
		'questions_tagged_x' => '^ bezala etiketatutako galdera berriak',
		'recategorized' => 'kategoriaz aldatuta',
		'recent_activity_in_x' => 'Aktibitate berria ^ -(e)n',
		'recent_activity_title' => 'Aktibitate berria',
		'recent_as_in_x' => 'Berriki  ^ -(e)n erantzun diren galderak',
		'recent_as_title' => 'Berriki erantzun diren galderak',
		'recent_cs_in_x' => 'Berriki ^ -(e)n idatzi diren iruzkinak',
		'recent_cs_title' => 'Berriki idatzi diren iruzkinak',
		'recent_qs_as_in_x' => 'Galdera eta erantzun berriak ^ -(e)n',
		'recent_qs_as_title' => 'Galdera eta erantzun berriak',
		'recent_qs_in_x' => 'Galdera berriak ^ -(e)n',
		'recent_qs_title' => 'Galdera berriak',
		'related_qs_title' => 'Erlazionatutako galderak',
		'remove_favorites' => 'Nire gogokoenetatik ezabatu',
		'remove_x_favorites' => '^ nire gogokoenetatik ezabatu',
		'reopened' => 'berriz irekita',
		'reshown' => 'berriz erakusten da',
		'results_for_x' => '^ -(e)rako emaitzak bilatu',
		'retagged' => 'etiketaz aldatu da',
		'save_button' => 'Aldaketak gorde',
		'search_button' => 'Bilatu',
		'search_explanation' => 'Mesedez, idatzi bilaketa eremuan eta berriro saiatu',
		'search_title' => 'Bilaketaren emaitzak',
		'selected' => 'hautatua',
		'send_button' => 'Bidali',
		'suggest_ask' => 'Komunitatean parte hartu, ^1galdera egin^2.',
		'suggest_category_qs' => 'Gehiago ikusteko, ^1kategoria honetako galderak^2 sakatu.',
		'suggest_qs_tags' => 'Gehiago ikusteko, ^1galdera zerrenda osoa^2 edo ^3gehien erabiltzen diren etiketak^4 sakatu.',
		'suggest_qs' => 'Gehiago ikusteko, ^1galdera zerrenda osoa^2 sakatu.',
		'unanswered_qs_in_x' => 'Erantzun gabeko galdera berriak ^ -(e)n',
		'unanswered_qs_title' => 'Erantzun gabeko galdera berriak',
		'unselected_qs_in_x' => 'Erantzun hautatua ez duten galderak ^ -(e)n',
		'unselected_qs_title' => 'Erantzun hautatua ez duten galdera berriak',
		'unupvoteda_qs_in_x' => 'Boto positiboa duen erantzun gabeko galderak ^ -(e)n',
		'unupvoteda_qs_title' => 'Boto positiboa duen erantzun gabeko galdera berriak',
		'upload_limit' => 'Gauza gehiegi ido dira - mesedez, saiatu berriro ordubete barru',
		'view_q_must_be_approved' => 'Zure kontua baieztatu behar da galdera orrialdeak ikusi ahal izateko.',
		'view_q_must_confirm' => 'Mesedez, ^5zure email-a baieztatu^6 galderen orrialdea ikusteko.',
		'view_q_must_login' => 'Mesedez, ^1saioa hasi^2 edo ^3erregistratu^4 galderen orrialdea ikusteko.',
		'viewed_qs_in_x' => 'Gehien ikusitako galderak ^ -(e)n',
		'viewed_qs_title' => 'Gehien ikusitako galderak',
		'vote_disabled_approve' => 'Zure kontua baieztatu behar da botoa eman ahal izateko',
		'vote_disabled_down' => 'Bakarrik erabiltzaile batzuek eman dezakete boto negatiboa',
		'vote_disabled_down_approve' => 'Zure kontua baieztatu behar da botoa negatiboa eman ahal izateko',
		'vote_disabled_hidden_a' => 'Ezin dituzu erantzun ezkutuak bozkatu',
		'vote_disabled_hidden_q' => 'Ezin dituzu galdera ezkutuak bozkatu',
		'vote_disabled_level' => 'Bakarrik erabiltzaile batzuek bozkatu dezakete',
		'vote_disabled_my_a' => 'Ezin dituzu zure erantzunak bozkatu',
		'vote_disabled_my_q' => 'Ezin dituzu zure galderak bozkatu',
		'vote_disabled_q_page_only' => 'Mesedez, galdera ikusi bozkatzeko',
		'vote_down_must_confirm' => 'Mesedez, ^5zure posta elektronikoa baieztatu^6 boto negatiboa emateko.',
		'vote_down_popup' => 'Sakatu boto negatiboa emateko',
		'vote_limit' => 'Boto gehiegi jaso dira - mesedez, saiatu berriro ordubete barru',
		'vote_must_confirm' => 'Mesedez, ^5zure posta elektronikoa baieztatu^6 bozkatzeko.',
		'vote_must_login' => 'Mesedez, ^1saioa hasi^2 edo ^3erregistratu^4 bozkatzeko.',
		'vote_not_allowed' => 'Ezin da honetaz bozkatu',
		'vote_up_popup' => 'Sakatu boto positiboa emateko',
		'voted_down_popup' => 'Boto negatiboa eman duzu - sakatu botoa kentzeko',
		'voted_qs_in_x' => 'Highest voted questions in ^',
		'voted_qs_title' => 'Gehien bozkatutako galderak',
		'voted_up_popup' => 'Boto positiboa eman duzu - sakatu botoa kentzeko',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => 'orain dela ^',
		'x_answers' => '^ erantzun',
		'x_comments' => '^ iruzkin',
		'x_days' => '^ egun',
		'x_disliked' => '^ negatibo',
		'x_flags' => '^ marka',
		'x_hours' => '^ ordu',
		'x_liked' => '^ positibo',
		'x_minutes' => '^ minutu',
		'x_months' => '^ hilabete',
		'x_points' => '^ puntu',
		'x_questions' => '^ galdera',
		'x_seconds' => '^ segundu',
		'x_tags' => '^ etiketa',
		'x_users' => '^ erabiltzaile',
		'x_views' => '^ ikusi',
		'x_votes' => '^ boto',
		'x_weeks' => '^ aste',
		'x_years' => '^ urte',
		'email_error' => "An error occurred trying to send the email.",
		'file_upload_limit_exceeded' => "Fitxategiaren tamaina zerbitzariaren mugak gainditzen ditu.",
		'since_x' => "^ -(e)tatik",
		'to_x' => " ^ arte",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
