<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-admin.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => 'Hurrengo widget-ak jarduenan daude:',
		'add_category_button' => 'Kategoria gehitu',
		'add_field_button' => 'Eremua gehitu',
		'add_link_button' => 'Esteka gehitu',
		'add_link_link' => ' - ^1esteka gehitu^2',
		'add_new_field' => 'Eremu berria gehitu',
		'add_new_title' => 'Titulu berria gehitu',
		'add_page_button' => 'Orrialdea gehitu',
		'add_title_button' => 'Titulua gehitu',
		'add_widget_button' => 'Widget-a gehitu',
		'add_widget_link' => ' - ^1widget-a gehitu^2',
		'admin_title' => 'Administrazio gunea',
		'after_footer' => 'Orri-oineko esteken ostean',
		'after_main_menu' => 'Goiburuko erlaitzen ostean',
		'after_x_tab' => '"^" erlaitzaren ostean',
		'after_x' => '"^" ostean',
		'moderate_title' => 'Moderatu',
		'basic_editor' => 'Oinarrizko editorea',
		'before_main_menu' => 'Goiburuko erlaitzen aurrean',
		'blobs_directory_error' => 'QA_BLOBS_DIRECTORY izena duen ^ direktorioa ezin da idatzi web zerbitzariaren bidez.',
		'blobs_move_complete' => 'Igotako irudien eta dokumentuen migrazioa bete da.',
		'blobs_move_moved' => '^2 igotako irudietatik eta dokumentuetatik ^1 -(r)en migrazioa bete da',
		'blobs_stop' => 'Migrazioa gelditu',
		'blobs_to_db' => 'Blob-ak datubasera',
		'blobs_to_db_note' => '- igotako irudi eta dokumentu guztiak diskoetatik datu-basera migratu',
		'blobs_to_disk' => 'Blob-ak diskoetara',
		'blobs_to_disk_note' => '- igotako irudi eta dokumentu guztiak datu-basetik diskoetara migratu',
		'block_button' => 'blokeatu',
		'block_ips_note' => 'Gidoia erabili tarteentzako edo * edozein zenbaki adierazteko. Adibideak: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => '* erabili edozein letra adierazteko. Adibideak: dezake (dezake hitz soila adierazten du), dezake* (dezake, dezaket, dezakete hautatuko ditu), *ezake (dezake, lezake hautatuko ditu)',
		'cancel_mailing_button' => 'Mailing-a gelditu',
		'categories_introduction' => 'Kategoriak gehitzen hasteko, \'Kategoria gehitu\' botoia sakatu.',
		'categories_not_shown' => 'Galdera batzuk erakutsiko ez diren kategoriak dauzkate.',
		'categories_title' => 'Kategoriak',
		'categories' => 'Kategoriak',
		'category_add_sub' => 'azpikategoria gehitu',
		'category_added' => 'Kategoria gehitu da',
		'category_already_used' => 'Beste kategoriagatik erabilita',
		'category_default_slug' => 'kategoria-^',
		'category_description' => 'Kategoriaren deskribapena (hautazkoa):',
		'category_max_depth_x' => 'Ezarpen batzuk ezkutatu ahal dira kategoria batek ^ maila baino gehiago izan ez dezan.',
		'category_move_parent' => 'guraso desberdin batera mugitu',
		'category_name_first' => 'Lehenengo kategoriaren izena:',
		'category_name' => 'Kategoriaren izena:',
		'category_no_add_subs_x' => 'Kategoria honek ezin ditu azpikategoria gehiago izan ^ maila dituelako.',
		'category_no_delete_subs' => 'Kategoria hau ezin da ezabatu azpikategoriak dituelako.',
		'category_no_sub_error' => '^q kategoria honetako galderek ez dute azpikategoriarik - ^1azpikategoria esleitu^2',
		'category_no_sub_to' => '^ -(r)en azpikategoria ez duten galderak hona mugitu:',
		'category_no_subs' => 'Bat ere ez',
		'category_none_error' => '^q galderek ez dute kategoriarik - ^1kategoria esleitu^2',
		'category_none_to' => 'Kategoria gabeko galderak hona mugitu:',
		'category_parent' => 'Guraso kategoria:',
		'category_saved' => 'Kategoria gorde da',
		'category_slug' => 'Category slug - URL fragment:', 'Kategoriaren ezizena - URL-aren zatia:',
		'category_subs' => 'Azpikategoriak:',
		'category_top_level' => 'No parent (top level)', 'Gurasorik gabe (goiko maila)',
		'characters' => 'karaktere',
		'check_language_suffix' => ' - ^1hizkuntza fitxategiak egiaztatu^2',
		'click_name_edit' => 'Orrialde edo esteka pertsonalizatuak:',
		'database_cleanup' => 'Datu-basearen garbiketarako ekintzak',
		'delete_category_reassign' => 'Kategoria ezabatu eta bere galderak hona esleitu:',
		'delete_category' => 'Kategoria ezabatu',
		'delete_field' => 'Eremua ezabatu',
		'delete_hidden_complete' => 'Menpekorik gabeko ezkutuko sarrera guztiak ezabatu dira',
		'delete_hidden_note' => ' - ezkutuko galdera, erantzun eta menpekorik gabeko iruzkin guztiak',
		'delete_hidden' => 'Ezkutuko sarrerak ezabatu',
		'delete_link' => 'Esteka ezabatu',
		'delete_page' => 'Orrialdea ezabatu',
		'delete_stop' => 'Ezabaketa gelditu',
		'delete_title' => 'Titulua ezabatu',
		'delete_widget_position' => 'Posizio honetako widget hau ezabatu',
		'edit_custom_page' => 'Pertsonalizatutako orrialdea editatu',
		'edit_field' => ' - ^1eremua editatu^2',
		'edit_link' => ' - ^1esteka editatu^2',
		'edit_page' => ' - ^1orrialdea editatu^2',
		'edit_title' => ' - ^1izenburua editatu^2',
		'emails_per_minute' => 'minuturoko emailak',
		'emails_title' => 'Emailak',
		'feed_link_example' => 'Ereduzko iturburua',
		'feed_link' => 'Iturburua',
		'feeds_title' => 'RSS iturburuak',
		'field_link_url' => 'Estekatutako URL-a',
		'field_multi_line' => 'Testu lerro anitzak',
		'field_name' => 'Eremu izena:',
		'field_single_line' => 'Testu lerro bakarra',
		'field_type' => 'Eremu mota:',
		'first' => 'Lehenengoa',
		'flagged_title' => 'Markatuak',
		'form_security_expired' => 'Formularioaren segurtasun kodearen epea amaitu da - mesedez, berriro saiatu',
		'from_anon' => 'Ezezagunen igorpenak:',
		'from_users' => 'Erabiltzaileen igorpenak:',
		'general_title' => 'Ezarpen orokorrak',
		'hidden_answers_deleted' => ' ^2 menpekorik gabeko erantzun ezkutuetatik ^1 ezabatuta...',
		'hidden_comments_deleted' => ' ^2 iruzkin ezkutuetatik ^1 ezabatuta...',
		'hidden_questions_deleted' => ' ^2 menpekorik gabeko galdera ezkutuetatik ^1 ezabatuta...',
		'hotness_factors' => 'Galdera nabarmenduen garrantzi erlatiboa:',
		'hidden_title' => 'Ezkutuak',
		'ip_address_pages' => 'Ip helbideen orrialdeak',
		'layout_title' => 'Diseinua',
		'link_name' => 'Estekarako testua:',
		'link_new_window' => 'Esteka leiho berri batean ireki',
		'link_url' => 'Estekaren URL-a (QA erroarekiko absolutu edo erlatiboa):',
		'lists_title' => 'Zerrendak',
		'mailing_complete' => 'Mailing-a burutu da',
		'mailing_explanation' => 'Erabiltzaileek suskribapena ezeztatu dezakete haien kontu orrialdetan.',
		'mailing_progress' => ' ^2 erabiltzailetik ^1 -(r)en mailing-a burututa...',
		'mailing_title' => 'Mailing',
		'mailing_unsubscribe' => 'Suskribapena ezeztatzeko esteka bat gehituko da mezu bakoitzaren amaieran.',
		'maintenance_admin_only' => 'Zure webgunea ^1mantentze-lanetan^2 dago eta erabiltzaile arruntak ezin dira sartu.',
		'maximum_x' => ' (max ^)',
		'approve_users_title' => 'Erabiltzaileak baieztatu',
		'module_x_database_init' => ' ^1 ^2 modulua ^3datu-basearen hasieraketa^4 behar du.',
		'most_flagged_title' => 'Markatutako edukia',
		'mysql_version' => 'MySQL bertsioa:',
		'nav_links_explanation' => 'Hurrengo estekak orrialde guztietan erakutsi:',
		'nav_qa_is_home' => 'Q&A (hasiera orrialderako estekak)',
		'neat_urls_note' => ' (^1htaccess^2 fitxategia behar da)',
		'no_approve_found' => 'Onesteko edukirik gabe',
		'no_classification' => 'Bat ere ez',
		'no_flagged_found' => 'Markatutako edukirik gabe',
		'no_hidden_found' => 'Ezkutuko edukirik gabe',
		'no_image_gd' => 'Instalatutako PHP bertsioa irudientzako GD euskarria gabe konpilatu da, erabiltzaileek ezin dute profilezko argazkia zuzenean igo.',
		'no_link' => 'Esteka gabe',
		'no_multibyte' => 'Instalatutako PHP bertsioa multibyte kateentzako euskarri gabe konpilatu da. Bilaketak ez dira hain eraginkorrak izango karaktere ez erromatarrentzako.',
		'no_privileges' => 'Administratzaileek bakarrik sar daitezke orrialde honetan.',
		'no_unapproved_found' => 'Onesteko erabiltzailerik gabe',
		'not_logged_in' => 'Mesedez, ^1saioa hasi^2 administratzaile moduan orrialde honerata sartzeko.',
		'opposite_main_menu' => 'Goiburuko erlaitz menuaren muturrean',
		'options_reset' => 'Ezarpenak berrasieratu dira',
		'options_saved' => 'Ezarpenak gorde dira',
		'options' => 'ezarpenak',
		'page_already_used' => 'Jadanik orrialde batek erabiltzen du',
		'page_content_html' => 'Orrialdean erakusteko edukia - HTML baimentzen da:',
		'page_default_slug' => 'orrialdea-^',
		'page_heading' => 'Goiburuan erakusteko testua:',
		'page_name' => 'Orrialdearen izena (erlaitzetan eta esteketan ere erabiliko da):',
		'page_slug' => 'Orrialdearen ezizena (URL-aren zatia):',
		'pages_explanation' => '\'Orrialdea gehitu\' botoian sakatu zure QA gunean pertsonalizatutako edukia gehitzeko, edo \'Esteka gehitu\' beste edozein webgunearekin esleitzeko.',
		'pages_title' => 'Orrialdeak',
		'pause_mailing_button' => 'Mailing-a gelditu',
		'per_ip_hour' => 'IP/orduro',
		'per_user_hour' => 'Erabiltzaile/orduro',
		'permissions_title' => 'Baimenak',
		'permit_to_view' => 'Visible for:', 'Hauentzako ikusgaia:',
		'php_version' => 'PHP bertsioa:',
		'pixels' => 'pixelak',
		'plugin_module' => ' (plugin modulua: ^)',
		'plugin_pages_explanation' => 'Hurrengo orrialdeak pluginen bidez eskuragarri daude:',
		'plugins_title' => 'Pluginak',
		'points_defaults_shown' => 'Lehenetsitako balioak erakusten dira, baina ORAINDIK EZ DIRA EZARRI:',
		'points_required' => 'Titulu bat jasotzeko behar diren puntuak:',
		'points_title' => 'Puntuak',
		'points' => 'puntu',
		'position' => 'Posizioa:',
		'posting_title' => 'Argitalpenak',
		'profile_fields' => 'Erabiltzaileen profilen eremu gehigarriak:',
		'q2a_build_date' => 'Eraikitze data:',
		'q2a_db_size' => 'Datu-basearen tamaina:',
		'q2a_db_version' => 'Q2A datu-basearen bertsioa:',
		'q2a_latest_version' => 'Azken bertsioa:',
		'q2a_version' => 'Question2Answer bertsioa:',
		'question_lists' => 'Galdera zerrenda',
		'question_pages' => 'Galdera orrialdeak',
		'recalc_categories_backpaths' => ' ^2 kategorietatik ^1 -(r)en URL bideak birkalkulatzen...',
		'recalc_categories_complete' => 'Kategoria guztiak birkalkulatu dira.',
		'recalc_categories_note' => ' - kategoriak zenbatzeko eta kategorien sarrerentzako',
		'recalc_categories_recounting' => ' ^2 kategorietatik ^1 -(r)en galderak birkalkulatzen...',
		'recalc_categories_updated' => ' ^2 argitalpenetik ^1 birkalkulatuta...', 
		'recalc_categories' => 'Kategoriak birkalkulatu',
		'recalc_points_complete' => 'Erabiltzaileen puntu guztiak birkalkulatu dira.',
		'recalc_points_note' => ' - erabiltzaileen sailkapenarentzat eta erakutsitako puntuentzat',
		'recalc_points_recalced' => ' ^2 erabiltzaileetatik ^1 -(r)en puntuak birkalkulatuta...',
		'recalc_points_usercount' => 'Zenbatetsitako erabiltzaile kopuru totala...',
		'recalc_points' => 'Erabiltzaile puntuak birkalkulatu',
		'recalc_posts_count' => 'Galdera, erantzun eta iruzkin kopuru totala lortzen...',
		'recalc_stop' => 'Birkalkulaketa gelditu',
		'recent_approve_title' => 'Onesteko eduki berria',
		'recent_hidden_title' => 'Berriki ezkutatutako edukia',
		'recount_posts_as_recounted' => ' ^2 sarreretatik ^1 -(r)en erantzunak eta aktibitate maila zenbatuta...',
		'recount_posts_complete' => 'Argitalpen guztiak berriz zenbatu dira',
		'recount_posts_note' => ' - argitalpen bakoitzeko aktibitate maila eta boto, erantzun eta marka kopurua',
		'recount_posts_stop' => 'Zenbateka gelditu',
		'recount_posts_votes_recounted' => ' ^2 argitalpenetatik ^1 -(r)en boto eta markak zenbatuta...',
		'recount_posts' => 'Argitalpenak berriz zenbatu',
		'refill_events_complete' => 'Gertaera sekuentzia guztiak bete dira',
		'refill_events_note' => ' - erabiltzaile bakoitzaren eguneraketa zerrendarako',
		'refill_events_refilled' => ' ^2 galderetatik ^1 beteta...',
		'refill_events' => 'Gertaera sekuentzia bete',
		'registration_fields' => 'erregistratzeko eremuak gehitu',
		'reindex_content' => 'Edukia berriz indexatu',
		'reindex_content_note' => ' - iradokitako bilaketentzako eta erlazionatutako galderentzako',
		'reindex_content_stop' => 'Indexaketa gelditu',
		'reindex_pages_reindexed' => ' ^2 orrialdetatik ^1 indexatuta...',
		'reindex_posts_complete' => 'Argitalpen guztiak berriz indexatu dira.',
		'reindex_posts_reindexed' => ' ^2 argitalpenetatik ^1 berriz indexatuta...',
		'reindex_posts_wordcounted' => ' ^2 hitzetik ^1 berriz zenbatuta...',
		'requires_php_version' => 'Desgaituta - PHP ^ edo berriagoa behar da',
		'requires_q2a_version' => 'Desgaituta - Question2Answer ^ edo berriagoa behar da',
		'reset_options_button' => 'Lehenetsitako balioak berrasieratu',
		'resume_mailing_button' => 'Mailing-a jarraitu',
		'save_options_button' => 'Ezarpenak gorde',
		'save_recalc_button' => 'Gorde eta birkalkulatu',
		'save_view_button' => 'Gorde eta ikusi',
		'send_test_button' => 'Testa bidali',
		'show_defaults_button' => 'Lehenetsitako balioak erakutsi',
		'show_on_register_form' => 'Eremua erakutsi erabiltzaileen erregistro formularioan',
		'slug_bad_chars' => 'Ezizenean ezin dira hurrengo karaktereak idatzi: ^',
		'slug_reserved' => 'Ezizen hau beste orrialde batek erabili dezan gordeta dago',
		'spam_title' => 'Spam',
		'start_mailing_button' => 'Mailing-a hasi',
		'stats_title' => 'Estatistikak',
		'stop_recalc_warning' => 'Datu-basearen garbiketa egiten ari da. Orrialde hau ixten baduzu, ataza geldituko da.',
		'tag_pages' => 'Etiketen orrialdeak',
		'tags_and_categories' => 'Etiketak eta kategoriak',
		'tags_not_shown' => 'Galdera batzuk erakutsiko ez diren etiketak dauzkate.',
		'tags' => 'Etiketak',
		'test_sent_to_x' => 'Test mezua ^ -ri bidali da',
		'title_already_used' => 'Balio hau beste titulu bat jadanik erabiltzen du', 
		'top_level_categories' => 'Goi mailako kategoriak:',
		'total_as' => 'Erantzun kopuru totala:',
		'total_cs' => 'Iruzkin kopuru totala:',
		'total_qs' => 'Galdera kopuru totala:',
		'unnamed_plugin' => 'Izen gabeko plugina',
		'upgrade_db' => 'Zure Question2Answer datu-basea ^1eguneratu^2 behar da bertsio honetarako.',
		'url_format_note' => ' ^ etiketa daukaten ezarpenak zure webguneko konfigurazioarekin funtzionatzen dute. Bilatzaileak (SEO) optimizatzeko, erabili lehenengo ^ aukera.',
		'user_pages' => 'Erabiltzaile orrialdeak',
		'user_title' => 'Erabiltzale titulua (HTML baimentzen du):',
		'user_titles' => 'Puntuetan oinarritutako erabiltzaile tituluak:',
		'users_active' => 'Erabiltzaile aktiboak:',
		'users_must_have' => 'Erabiltzaileek izan beharreko puntuak',
		'users_posted' => 'Argitalpenak egin dituzten erabiltzaileak:',
		'users_registered' => 'Erregistratutako erabiltzaileak:',
		'users_title' => 'Erabiltzaileak',
		'users_voted' => 'Botozkatu duten erabiltzaileak:',
		'version_get_x' => "ikusi ^",
		'version_requires_php' => ' ^1 PHP ^2 behar du',
		'version_requires_q2a' => ' ^1 Q2A ^2 behar du',
		'version_latest_unknown' => 'azkenengo bertsioa ezezaguna',
		'version_latest' => 'azkenengoa',
		'viewing_title' => 'Itxura',
		'widget_all_pages' => 'Orrialde guztietan widget-a erakutsi posizio honetan',
		'widget_global_options' => ' - ^1ezarpenak^2',
		'widget_name' => 'Widget-aren izena:',
		'widget_no_positions' => 'Widget hau ahal diren posizio guztietan gehitu da.',
		'widget_not_available' => 'Widget hau ez dago erabilgarri. Agian wiget-a hornitzen duen plugina ez dago instalatuta.',
		'widget_pages_explanation' => 'Widget hau posizio honetan erakutsi hurrengo orrialdeetan:',
		'widgets_explanation' => 'Erabil daitezkeen widget-ak:',
		'approve_user_popup' => "Erabiltzailea baieztatu",
		'block_user_popup' => "Erabiltzailea blokeatu",
		'reset_options_confirm' => "Ziur zaude orrialde honetako lehenetsitako balioak berrasieratu nahi dituzula?",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
